FROM rust:latest
RUN rustup target add wasm32-unknown-unknown
RUN cargo install trunk --locked
RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n lts
VOLUME /front
WORKDIR /front
RUN npm install -D tailwindcss-animated
RUN npm install -D daisyui@latest
COPY . .
EXPOSE 8080
CMD trunk serve --release --address 0.0.0.0