name: 'Release'

on:
  push: 
    branches:
      - 'release/**'
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'img/**'
      - 'locales/**'
      - 'index.html'
      - 'dockerfile'
      - 'cargo.toml'
      - 'cargo.lock'
      - 'Trunk.toml'
      - 'package.json'
      - 'package-lock.json'
      - 'tailwind.config.js'

env:
  image_name: ${{ secrets.REGISTRY_NAME }}/peto-main-front

jobs:
    push-to-registry:
      runs-on: ubuntu-latest
      timeout-minutes: 30
  
      steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      # build and push containers
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.image_name }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
